### ISSUE TITLE
using on predis php client

### ISSUE THREAD

**Issue by ihabhamad** [RedBeardLab/zeeSQL-doc#2]
on testing on Laravel  Redis (Predis lib)
$data = Redis::connection('test')->executeRaw(['ZEESQL.QUERY',"DB","COMMAND SELECT * FROM foo"]);
or 
$data = Redis::connection('test')->executeRaw(['ZEESQL.QUERY',"DB COMMAND ","SELECT * FROM foo"]);
or 
$data = Redis::connection('test')->executeRaw(['ZEESQL.QUERY',"DB COMMAND SELECT * FROM foo"]);

return Command incomplete, no `COMMAND` nor `STATEMENT` fields"

and 

$data = Redis::connection('test')->executeRaw(['ZEESQL.QUERY DB COMMAND'," SELECT * FROM foo"]);

return "ERR unknown command `ZEESQL.QUERY DB COMMAND`, with args beginning with: ` SELECT * FROM foo`, "

any idea??

![image](https://user-images.githubusercontent.com/16678100/184520256-c63b72db-83ab-42a2-af00-f5970b5d3507.png)

That's in Redis monitor the client not compatible?

**Comment by ihabhamad** [comment]
after testing phpredis extension returns the same error

you need to accept quotation marks in parameters

for example 
$redis->rawCommand('set','fo','bar');
in monitor "set" "fo" "bar"
Redis accept that command and parameters
but  
"ZEESQL.EXEC" "DB COMMAND" "select * from mydb"
that's not acceptable
please update your module to work with PHP Redis clients

**Comment by siscia** [comment]
Can you try what to me seems the most obvious?

```
 $data = Redis::connection('test')->executeRaw(['ZEESQL.QUERY',"DB","COMMAND",  "SELECT * FROM foo"]);
```

So you are telling ZEESQL to query, then what database, then that you are executing a command and finally the command you are executing.

**Comment by ihabhamad** [comment]
@siscia thats works
![image](https://user-images.githubusercontent.com/16678100/185814181-30656974-3a12-4aea-91b4-b7049e0d8095.png)

![image](https://user-images.githubusercontent.com/16678100/185814202-716ad128-c8fe-45fe-8c25-03dcb148ee7e.png)

**Comment by siscia** [comment]
That's great!

Glad to help :)
