### ISSUE TITLE
 Unable to Load ZeeSQL License Page

### ISSUE THREAD

**Issue by v629** [RedBeardLab/zeeSQL-doc#3]
Hi there,

I hope this message finds you well. I wanted to bring to your attention an issue I'm encountering with the ZeeSQL website.

I've been attempting to access the ZeeSQL License page at https://license.zeesql.com/, but unfortunately, the page is not loading for me. I've tried accessing it from multiple devices and browsers, but the issue persists consistently.

I believe there might be an underlying technical problem causing the page not to load as expected. As a user who is interested in ZeeSQL, I'm eager to learn more about the licensing details, and this hindrance is preventing me from doing so.

Thank you for your attention to this matter. I look forward to your response and resolution of this issue.

Best regards,
**Vratik Pathak**

**Comment by siscia** [comment]
Hey Vratik,

I'll reach out by email ASAP.

Sorry for it.
